jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
]
urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    
    path('add-to-likeproduct/', views.add_to_likeproduct, name="add-to-likeproduct"),
    path('remove-likeproduct/<int:cart_id>/', views.remove_likeproduct, name="remove-likeproduct"),
    path('plus-likeproduct/<int:cart_id>/', views.plus_likeproduct, name="plus-likeproduct"),
    path('minus-likeproduct/<int:cart_id>/', views.minus_likeproduct, name="minus-likeproduct"),
    path('likeproduct/', views.likeproduct, name="likeproduct"),
    path('orders/', views.orders, name="orders"),

    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),


    path('testimonials', views.testimonials, name="testimonials"),
    path('services', views.services, name="services"),
    path('contact',views.contact,name="contact"),
    
    path('forgot_otp',views.forgot_otp,name="forgot_otp"),
    path('forgot_password',views.forgot_pass,name="forgot_pass"),
    path('new_pass',views.new_pass,name="new_pass"),
    path("checkout",views.checkout,name="checkout"),
    path("cod",views.cod,name="cod"),
    path('success',views.success,name="success"),
    path('cancle',views.cancle,name="cancle"),
    
    # path('verification/', include('verify_email.urls')),	
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/forms.py
from django.contrib.auth import password_validation
from store.models import Address
from django import forms
import django
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import CharField
from django.utils.translation import gettext, gettext_lazy as _



class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['locality', 'city', 'state']
        widgets = {'locality':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Popular Place like Restaurant, Religious Site, etc.'}), 'city':forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}), 'state':forms.TextInput(attrs={'class':'form-control', 'placeholder':'State or Province'})}


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'auto-focus':True, 'class':'form-control', 'placeholder':'Current Password'}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'New Password'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'Confirm Password'}))


class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete':'email', 'class':'form-control'}))


class SetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}))

store/views.py
import django
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from store.models import Address, Cart, Category, Order, Product,Email,Contactus
from django.shortcuts import redirect, render, get_object_or_404
from .forms import RegistrationForm, AddressForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator # for Class Based Views
from .models import *
from django.contrib import messages
import ssl
from .models import OTP_Data
import random
import smtplib
from email.message import EmailMessage
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from verify_email.email_handler import send_verification_email
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages #import messages
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.http import HttpResponse
import datetime
import stripe


# Create your views here.

def home(request):
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    if request.method=="POST":
        SUBSCRIBER=request.POST.get('email')
        data=Email(Email=SUBSCRIBER)
        data.save()
    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'store/index.html', context)


def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    context = {
        'product': product,
        'related_products': related_products,

    }
    return render(request, 'store/detail.html', context)

@login_required
def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories':categories})

@login_required
def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True)
    context = {
        'category': category,
        'products': products,
        'categories': categories,
    }
    return render(request, 'store/category_products.html', context)


# Authentication Starts Here
class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})
    
    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            inactive_user = send_verification_email(request, form)
            messages.success(request, "Congratulations! Registration Successful!")
        return render(request, 'account/register.html', {'form': form})
    
@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'addresses':addresses, 'orders':orders})


@method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user=request.user
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            reg = Address(user=user, locality=locality, city=city, state=state)
            reg.save()
            messages.success(request, "New Address Added Successfully.")
        return redirect('store:profile')


@login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Address removed.")
    return redirect('store:profile')

@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    # Check whether the Product is alread in Cart or Not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()
    messages.success(request, "Product Added Succesfully")
    return redirect('store:cart')


@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)
    shipping_amount = decimal.Decimal(10)
    # using list comprehension to calculate total amount based on quantity and shipping
    cp = [p for p in Cart.objects.all() if p.user==user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    addresses = Address.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'shipping_amount': shipping_amount,
        'total_amount': amount + shipping_amount,
        'addresses': addresses,
    }
    return render(request, 'store/cart.html', context)


@login_required
def remove_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
        messages.success(request, "Product removed from Cart.")
    return redirect('store:cart')


@login_required
def plus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        cp.quantity += 1
        cp.save()
    return redirect('store:cart')


@login_required
def minus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        # Remove the Product if the quantity is already 1
        if cp.quantity == 1:
            cp.delete()
        else:
            cp.quantity -= 1
            cp.save()
    return redirect('store:cart')


@login_required
def add_to_likeproduct(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    # Check whether the Product is alread in Cart or Not
    item_already_in_wishlist = Wishlist.objects.filter(product=product_id, user=user)
    if item_already_in_wishlist:
        cp = get_object_or_404(Wishlist, product=product_id, user=user)
        cp.save()
    else:
        Wishlist(user=user, product=product).save()
    messages.success(request, "Product Added Succesfully")
    return redirect('store:likeproduct')

@login_required
def likeproduct(request):
    user = request.user
    cart_products = Wishlist.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)

    context = {
        'cart_products': cart_products,
        'amount': amount,
    }
    return render(request, 'store/likeproduct.html', context)


@login_required
def remove_likeproduct(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Wishlist, id=cart_id)
        c.delete()
        messages.success(request, "Product removed from likedproduct.")
    return redirect('store:likeproduct')


@login_required
def plus_likeproduct(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Wishlist, id=cart_id)
        cp.save()
    return redirect('store:likeproduct')


@login_required
def minus_likeproduct(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Wishlist, id=cart_id)
        # Remove the Product if the quantity is already 1
        if cp.quantity == 1:
            cp.delete()
        else:
            cp.quantity -= 1
            cp.save()
    return redirect('store:likeproduct')




@login_required
def orders(request):
    all_orders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    return render(request, 'store/orders.html', {'orders': all_orders})





def testimonials(request):
    return render(request, 'store/testimonials.html')

def services(request):
    return render(request, 'store/services.html')

@login_required
def contact(request):
    if request.method=='POST':
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        phone=request.POST['phone']
        jwelery=request.POST['jwelery']
        design=request.FILES['design']
        subject=request.POST['subject']
        newcontact=Contactus.objects.create(firstname=firstname,lastname=lastname,phone=phone,jwelery=jwelery,design=design,subject=subject)  
        newcontact.save()
        messages.success(request, "Your Message send suucesfully!")
    return render(request, 'store/contact.html')

def forgot_otp(request):
    enable_otp = 0
    if request.method == "POST":
        email = request.POST.get("email_id")
        user = User.objects.filter(username = email)
        print(user)
        if user is not None:
            otp_generate = random.randrange(1000, 9999)
            # email_sender = 'manavmandli2990@gmail.com'

templates/store/cancle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="h5 text-uppercase mb-4 serc">Payment Not done!</h1>
    <h2 class="h5 text-uppercase mb-4 serc">Your Item is on Cart</h2>
    </div>
{% endblock content %}

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">₹{{cart_product.product.price}}</p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">₹{{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                  <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="{% url 'store:checkout' %}">Procceed to checkout<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">₹{{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+ ₹{{shipping_amount}}</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>₹{{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Select Shipping Address</h5>
                  
                  <form action="{% url 'store:cod' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}"> <strong>Address {{forloop.counter}}</strong> <br>
                        ( {{address.locality}}, {{address.city}}, {{address.state}} )
                        </div>
                      {% endfor %}
                    {% endif %}
                    
                    {% comment %} For Cash on Delivery {% endcomment %}
                    <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class="fas fa-dollar-sign mr-2"></i>Cash on Delivery</button>
                  </form>
                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your cart is empty.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{total_amount}}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}

templates/store/likeproduct.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
  <!-- HERO SECTION-->
  <section class="py-5 bg-light">
    <div class="container">
      <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
        <div class="col-lg-6">
          <h1 class="h2 text-uppercase mb-0">Wishlist</h1>
        </div>
        <div class="col-lg-6 text-lg-right">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
              <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Wishlist</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  {% if cart_products %}
  <section class="py-5">
    <h2 class="h5 text-uppercase mb-4">Wishlist Products</h2>

    {% include 'partials/_messages.html' %}

    <div class="row">
      <div class="col-lg-8 mb-4 mb-lg-0">
        <!-- CART TABLE-->
        <div class="table-responsive mb-4">
          <table class="table">
            <thead class="bg-light">
              <tr>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                <th class="border-0" scope="col"> </th>
              </tr>
            </thead>
            <tbody>

              {% for cart_product in cart_products %}
              <tr>
                <th class="pl-0 border-0" scope="row">
                  <div class="media align-items-center">

                    {% if cart_product.product.product_image %}
                    <a class="reset-anchor d-block animsition-link"
                      href="{% url 'store:product-detail' cart_product.product.slug %}"><img
                        src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}"
                        width="70" /></a>
                    {% else %}
                    <a class="reset-anchor d-block animsition-link"
                      href="{% url 'store:product-detail' cart_product.product.slug %}"><img
                        src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}"
                        width="70" /></a>
                    {% endif %}

                    <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link"
                          href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong>
                    </div>
                  </div>
                </th>
                <td class="align-middle border-0">
                  <p class="mb-0 small">₹{{cart_product.product.price}}</p>
                </td>
                <td class="align-middle border-0"><a class="reset-anchor"
                    href="{% url 'store:remove-likeproduct' cart_product.id %}"><i
                      class="fas fa-trash-alt small text-muted"></i></a></td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
        <!-- CART NAV-->
        <div class="bg-light px-4 py-3">
          <div class="row align-items-center text-center">
            <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm"
                href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
            </div>
          </div>
        </div>
        {% else %}

        <div class="text-center py-5">
          <h3 class="mb-3">Your Wishlist is empty.</h3>
          <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
        </div>
        {% endif %}
      </div>
    </div>
  </section>
</div>

{% endblock content %}

templates/store/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="h5 text-uppercase mb-4 sers">Payment done!</h1>
    <h2 class="h5 text-uppercase mb-4 sers">Your Order is on the Way...</h2>
    </div>
{% endblock content %}